/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import AccesoDatos.LibroData;
import Clases.Libro;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariel
 */
public class ActualizarLibros extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarLibros
     */
    private LibroData ld = new LibroData(); 
    private Libro libro = null;

    
    public ActualizarLibros() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfIdLibro = new javax.swing.JTextField();
        jbModificar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jlIsbn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfIsbn = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfTipo = new javax.swing.JTextField();
        jtfEditorial = new javax.swing.JTextField();
        jtfAutor = new javax.swing.JTextField();
        jrbActivo = new javax.swing.JRadioButton();
        jtfAnio = new javax.swing.JTextField();
        jlEjemplares = new javax.swing.JLabel();
        jtfEjemplares = new javax.swing.JTextField();
        jbAltaLibro = new javax.swing.JButton();
        jbBajaLibro = new javax.swing.JButton();
        jlDisponibilidad = new javax.swing.JLabel();
        jtfDisponibilidad = new javax.swing.JTextField();

        setResizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 221, 184));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 540));

        jPanel2.setBackground(new java.awt.Color(150, 186, 223));
        jPanel2.setPreferredSize(new java.awt.Dimension(840, 100));

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 48)); // NOI18N
        jLabel1.setText("Actualización de libros");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("ID libro");

        jtfIdLibro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jbModificar.setBackground(new java.awt.Color(150, 186, 223));
        jbModificar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbLimpiar.setBackground(new java.awt.Color(150, 186, 223));
        jbLimpiar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbLimpiar.setText("Limpiar campos");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(150, 186, 223));
        jbSalir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbBuscar.setBackground(new java.awt.Color(150, 186, 223));
        jbBuscar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jlIsbn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlIsbn.setText("ISBN");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Tipo");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Editorial");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Autor");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Estado");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Año");

        jtfIsbn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jtfNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jtfTipo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jtfEditorial.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jtfAutor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jrbActivo.setBackground(new java.awt.Color(255, 221, 184));
        jrbActivo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jrbActivo.setText("Activo");

        jtfAnio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jlEjemplares.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlEjemplares.setText("Ejemplares");

        jtfEjemplares.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jbAltaLibro.setBackground(new java.awt.Color(150, 186, 223));
        jbAltaLibro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbAltaLibro.setText("Dar de alta al libro");
        jbAltaLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaLibroActionPerformed(evt);
            }
        });

        jbBajaLibro.setBackground(new java.awt.Color(150, 186, 223));
        jbBajaLibro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbBajaLibro.setText("Dar de baja al libro");
        jbBajaLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaLibroActionPerformed(evt);
            }
        });

        jlDisponibilidad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlDisponibilidad.setText("Disponibilidad");

        jtfDisponibilidad.setEditable(false);
        jtfDisponibilidad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jbAltaLibro)
                        .addGap(18, 18, 18)
                        .addComponent(jbBajaLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jlEjemplares)
                            .addComponent(jlIsbn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jlDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jtfIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbBuscar))
                                .addComponent(jtfNombre)
                                .addComponent(jtfTipo)
                                .addComponent(jtfEditorial)
                                .addComponent(jtfAutor)
                                .addComponent(jrbActivo)
                                .addComponent(jtfAnio)
                                .addComponent(jtfEjemplares))
                            .addComponent(jtfDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIsbn)
                    .addComponent(jtfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jrbActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEjemplares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDisponibilidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificar)
                    .addComponent(jbLimpiar)
                    .addComponent(jbSalir)
                    .addComponent(jbAltaLibro)
                    .addComponent(jbBajaLibro))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose(); 
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        try{
            Integer idLibro = Integer.parseInt(jtfIdLibro.getText());
            libro = ld.buscarLibroPorId(idLibro);
            if(libro != null){
                jtfIsbn.setText(libro.getIsbn()+"");
                jtfNombre.setText(libro.getNombre());
                jtfTipo.setText(libro.getTipo());
                jtfEditorial.setText(libro.getEditorial());
                jtfAutor.setText(libro.getAutor());
                if (libro.isEstado()){
                    jrbActivo.setSelected(true);
                } else{
                    jrbActivo.setSelected(false);
                }
                jtfAnio.setText(libro.getAnio()+""); 
                jtfEjemplares.setText(libro.getEjemplares()+"");
                jtfDisponibilidad.setText(libro.getDisponibilidad()+"");
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");   
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        if(libro == null){
            JOptionPane.showMessageDialog(this, "Busque un libro por su ID para modificarlo");
        }else{
            try{
                Integer isbn = Integer.parseInt(jtfIsbn.getText());
                String nombre = jtfNombre.getText(); 
                String tipo = jtfTipo.getText();
                String editorial = jtfEditorial.getText(); 
                String autor = jtfAutor.getText();
                boolean estado = jrbActivo.isSelected(); 
                Integer anio = Integer.parseInt(jtfAnio.getText());
                Integer ejemplares = Integer.parseInt(jtfEjemplares.getText());
                
                
                if(nombre.isEmpty() || tipo.isEmpty() || editorial.isEmpty() || autor.isEmpty()){
                    JOptionPane.showMessageDialog(this, "No debe haber campos vacíos");
                } else{
                    libro.setIsbn(isbn);
                    libro.setNombre(nombre);
                    libro.setTipo(tipo);
                    libro.setEditorial(editorial);
                    libro.setAutor(autor);
                    libro.isEstado();
                    libro.setAnio(anio);
                    libro.setEjemplares(ejemplares);
                    ld.cambiarDisponibilidad(libro);
                    ld.modificarLibro(libro);
                    
                    //Seteo de campos con los valores actualizados
                    Integer idLibro = Integer.parseInt(jtfIdLibro.getText());
                    libro = ld.buscarLibroPorId(idLibro);
                    jtfIsbn.setText(libro.getIsbn()+"");
                    jtfNombre.setText(libro.getNombre());
                    jtfTipo.setText(libro.getTipo());
                    jtfEditorial.setText(libro.getEditorial());
                    jtfAutor.setText(libro.getAutor());
                    if (libro.isEstado()){
                        jrbActivo.setSelected(true);
                    } else{
                        jrbActivo.setSelected(false);
                    }
                    jtfAnio.setText(libro.getAnio()+""); 
                    jtfEjemplares.setText(libro.getEjemplares()+"");
                    jtfDisponibilidad.setText(libro.getDisponibilidad()+"");
                    
                    }
            }catch (NumberFormatException ex){
                JOptionPane.showMessageDialog(this,"Debe ingresar números enteros en los campos númericos");
            }
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbAltaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaLibroActionPerformed
        // TODO add your handling code here:
        if(libro!= null){
            ld.altaLibro(libro.getIdLibro());
        }else{
            JOptionPane.showMessageDialog(this, "No hay un libro seleccionado");    
        }
    }//GEN-LAST:event_jbAltaLibroActionPerformed

    private void jbBajaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaLibroActionPerformed
        // TODO add your handling code here:
        if(libro!= null){
            ld.eliminarLibro(libro.getIdLibro());
        }else{
            JOptionPane.showMessageDialog(this, "No hay un libro seleccionado");    
        }
    }//GEN-LAST:event_jbBajaLibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbAltaLibro;
    private javax.swing.JButton jbBajaLibro;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlDisponibilidad;
    private javax.swing.JLabel jlEjemplares;
    private javax.swing.JLabel jlIsbn;
    private javax.swing.JRadioButton jrbActivo;
    private javax.swing.JTextField jtfAnio;
    private javax.swing.JTextField jtfAutor;
    private javax.swing.JTextField jtfDisponibilidad;
    private javax.swing.JTextField jtfEditorial;
    private javax.swing.JTextField jtfEjemplares;
    private javax.swing.JTextField jtfIdLibro;
    private javax.swing.JTextField jtfIsbn;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTipo;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos(){
        jtfIdLibro.setText("");
        jtfIsbn.setText("");
        jtfNombre.setText("");
        jtfTipo.setText("");
        jtfEditorial.setText("");
        jtfAutor.setText("");
        jtfAnio.setText("");
        jrbActivo.setSelected(false);
        jtfEjemplares.setText("");
        libro = null;
    }
}

