/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoDatos.LectorData;
import Clases.Lector;
import javax.swing.JOptionPane;

/**
 *
 * @author ariel
 */
public class ActualizarDatos extends javax.swing.JInternalFrame {
    Lector lector = null; 
    LectorData ld = new LectorData();

    /**
     * Creates new form ActualizarDatos
     */
    public ActualizarDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbModificar = new javax.swing.JButton();
        jbAlta = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jlDniLector = new javax.swing.JLabel();
        jtfDniLector = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jlNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlDomicilio = new javax.swing.JLabel();
        jtfDomicilio = new javax.swing.JTextField();
        jlEstado = new javax.swing.JLabel();
        jrbActivo = new javax.swing.JRadioButton();
        jlTelefono = new javax.swing.JLabel();
        jtfTelefono = new javax.swing.JTextField();
        jlMail = new javax.swing.JLabel();
        jtfMail = new javax.swing.JTextField();
        jbBaja = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();

        setResizable(true);
        setPreferredSize(new java.awt.Dimension(800, 550));

        jPanel1.setBackground(new java.awt.Color(255, 221, 184));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 540));

        jPanel2.setBackground(new java.awt.Color(150, 186, 223));
        jPanel2.setPreferredSize(new java.awt.Dimension(840, 100));

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 48)); // NOI18N
        jLabel1.setText("Actualización de datos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jbModificar.setBackground(new java.awt.Color(150, 186, 223));
        jbModificar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbAlta.setBackground(new java.awt.Color(150, 186, 223));
        jbAlta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbAlta.setText("Dar de alta al socio");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(150, 186, 223));
        jbSalir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jlDniLector.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlDniLector.setText("DNI Socio");

        jtfDniLector.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jbBuscar.setBackground(new java.awt.Color(150, 186, 223));
        jbBuscar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jlNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlNombre.setText("Nombre");

        jtfNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jlDomicilio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlDomicilio.setText("Domicilio");

        jtfDomicilio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jlEstado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlEstado.setText("Estado");

        jrbActivo.setBackground(new java.awt.Color(255, 221, 184));
        jrbActivo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jrbActivo.setText("Activo");

        jlTelefono.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlTelefono.setText("Teléfono");

        jtfTelefono.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jlMail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlMail.setText("Mail");

        jtfMail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jbBaja.setBackground(new java.awt.Color(150, 186, 223));
        jbBaja.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbBaja.setText("Dar de baja al socio");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        jbLimpiar.setBackground(new java.awt.Color(150, 186, 223));
        jbLimpiar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbLimpiar.setText("Limpiar Campos");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlTelefono)
                        .addComponent(jlEstado)
                        .addComponent(jlNombre)
                        .addComponent(jlDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlDniLector)
                        .addComponent(jlMail))
                    .addComponent(jbModificar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfDniLector, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbBuscar))
                            .addComponent(jtfDomicilio)
                            .addComponent(jtfTelefono)
                            .addComponent(jtfMail, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(jrbActivo)
                            .addComponent(jtfNombre))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbAlta)
                        .addGap(18, 18, 18)
                        .addComponent(jbBaja)
                        .addGap(18, 18, 18)
                        .addComponent(jbLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jbSalir)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDniLector)
                    .addComponent(jtfDniLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDomicilio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstado)
                    .addComponent(jrbActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        try{
            Integer dni = Integer.parseInt(jtfDniLector.getText());
            String dniString = dni.toString();
            lector = ld.buscarLectorPorDni(dniString);
            if(lector != null){
                jtfNombre.setText(lector.getNombre()+"");
                jtfDomicilio.setText(lector.getDomicilio());
                jtfTelefono.setText(lector.getTelefono());
                jtfMail.setText(lector.getMail());
                if (lector.isEstado()){
                    jrbActivo.setSelected(true);
                } else{
                    jrbActivo.setSelected(false);
                }
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        if(lector == null){
            JOptionPane.showMessageDialog(this, "Busque un socio por su DNI para modificarlo");
        }else{
            String dni = jtfDniLector.getText();
            String nombre = jtfNombre.getText(); 
            String domicilio = jtfDomicilio.getText();
            String telefono = jtfTelefono.getText();
            boolean estado = jrbActivo.isSelected();
            String mail = jtfMail.getText();

            if(dni.isEmpty() || nombre.isEmpty() || domicilio.isEmpty() || telefono.isEmpty() || mail.isEmpty()){
                JOptionPane.showMessageDialog(this, "No debe haber campos vacíos");
            } else{
                lector.setDni(dni);
                lector.setNombre(nombre);
                lector.setDomicilio(domicilio);
                lector.setTelefono(telefono);
                lector.isEstado();
                lector.setMail(mail);
                ld.modificarLector(lector);
                    
                //Seteo de campos con los valores actualizados
                //int idLector = lector.getIdLector();
                lector = ld.buscarLectorPorDni(dni);
                jtfNombre.setText(lector.getNombre()+"");
                jtfDomicilio.setText(lector.getDomicilio());
                jtfTelefono.setText(lector.getTelefono());
                if (lector.isEstado()){
                    jrbActivo.setSelected(true);
                } else{
                    jrbActivo.setSelected(false);
                }
                jtfMail.setText(lector.getMail());
            }
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        // TODO add your handling code here:
        if(lector!= null){
            ld.activarLector(lector.getIdLector());
            if (lector.isEstado()){
                    jrbActivo.setSelected(true);
                } else{
                    jrbActivo.setSelected(false);
                }
        }else{
            JOptionPane.showMessageDialog(this, "No hay un socio seleccionado");    
        }
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        // TODO add your handling code here:
        if(lector!= null){
            ld.desactivarLector(lector.getIdLector());
            if (lector.isEstado()){
                    jrbActivo.setSelected(false);
                } else{
                    jrbActivo.setSelected(true);
                }
        }else{
            JOptionPane.showMessageDialog(this, "No hay un socio seleccionado");    
        }
    }//GEN-LAST:event_jbBajaActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        
    }//GEN-LAST:event_jbLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlDniLector;
    private javax.swing.JLabel jlDomicilio;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlMail;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JRadioButton jrbActivo;
    private javax.swing.JTextField jtfDniLector;
    private javax.swing.JTextField jtfDomicilio;
    private javax.swing.JTextField jtfMail;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
    private void limpiarCampos(){
        jtfDniLector.setText("");
        jtfNombre.setText("");
        jtfDomicilio.setText("");
        jtfMail.setText("");
        jtfTelefono.setText("");
        jrbActivo.setSelected(false);
        lector = null;
    }


}
