/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;


import AccesoDatos.LibroData;
import Clases.Libro;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariel
 */
public class BuscarLibros extends javax.swing.JInternalFrame {
    private LibroData ld = new LibroData(); 
    private Libro libro = null;
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form BuscarLibros
     */
    public BuscarLibros() {
        initComponents();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfBuscarXNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfBuscarXAutor = new javax.swing.JTextField();
        jbBuscarXNombre = new javax.swing.JButton();
        jbBuscarXAutor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLibros = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();
        jbLimpiarTabla = new javax.swing.JButton();

        setResizable(true);
        setPreferredSize(new java.awt.Dimension(850, 600));

        jPanel1.setBackground(new java.awt.Color(255, 221, 184));

        jPanel2.setBackground(new java.awt.Color(150, 186, 223));

        jlTitulo.setFont(new java.awt.Font("Sitka Subheading", 1, 48)); // NOI18N
        jlTitulo.setText("Buscar Libros");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jlTitulo)
                .addGap(253, 253, 253))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Buscar por nombre");

        jtfBuscarXNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Buscar por autor");

        jtfBuscarXAutor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jtfBuscarXAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBuscarXAutorActionPerformed(evt);
            }
        });

        jbBuscarXNombre.setBackground(new java.awt.Color(150, 186, 223));
        jbBuscarXNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbBuscarXNombre.setText("Buscar");
        jbBuscarXNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarXNombreActionPerformed(evt);
            }
        });

        jbBuscarXAutor.setBackground(new java.awt.Color(150, 186, 223));
        jbBuscarXAutor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbBuscarXAutor.setText("Buscar");
        jbBuscarXAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarXAutorActionPerformed(evt);
            }
        });

        jtLibros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jtLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtLibros.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jtLibros);

        jbSalir.setBackground(new java.awt.Color(150, 186, 223));
        jbSalir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbLimpiarTabla.setBackground(new java.awt.Color(150, 186, 223));
        jbLimpiarTabla.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbLimpiarTabla.setText("Limpiar tabla");
        jbLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbLimpiarTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalir)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfBuscarXNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3))
                            .addComponent(jbBuscarXNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbBuscarXAutor)
                            .addComponent(jtfBuscarXAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfBuscarXNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfBuscarXAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscarXAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarXNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpiarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBuscarXAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBuscarXAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBuscarXAutorActionPerformed

    private void jbBuscarXNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarXNombreActionPerformed
        // TODO add your handling code here:
        cargarLibrosNombre();
    }//GEN-LAST:event_jbBuscarXNombreActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBuscarXAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarXAutorActionPerformed
        // TODO add your handling code here:
        cargarLibrosAutor();
    }//GEN-LAST:event_jbBuscarXAutorActionPerformed

    private void jbLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarTablaActionPerformed
        // TODO add your handling code here:
        borrarFilasTabla();
    }//GEN-LAST:event_jbLimpiarTablaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscarXAutor;
    private javax.swing.JButton jbBuscarXNombre;
    private javax.swing.JButton jbLimpiarTabla;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtLibros;
    private javax.swing.JTextField jtfBuscarXAutor;
    private javax.swing.JTextField jtfBuscarXNombre;
    // End of variables declaration//GEN-END:variables
    
    private void armarCabeceraTabla(){
        ArrayList <Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID Libro");
        filaCabecera.add("ISBN");
        filaCabecera.add("Nombre");
        filaCabecera.add("Tipo");
        filaCabecera.add("Editorial");
        filaCabecera.add("Autor");
        filaCabecera.add("Estado");
        filaCabecera.add("Año");
        filaCabecera.add("Ejemplares"); 
        filaCabecera.add("Disponibilidad");
        for(Object it: filaCabecera){
            modelo.addColumn(it);
        }
        jtLibros.setModel(modelo);
    }
    private void cargarLibrosNombre(){
        borrarFilasTabla();
        String nombre = jtfBuscarXNombre.getText().trim(); // Elimina espacios en blanco alrededor del nombre
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el nombre del libro");
        } else {
            try {
                List<Libro> lista = (ArrayList) ld.buscarLibroPorNombre(nombre);
                for (Libro libro : lista) {
                    modelo.addRow(new Object[] {libro.getIdLibro(), libro.getIsbn(), libro.getNombre(), libro.getTipo(), libro.getEditorial(), libro.getAutor(), libro.isEstado(), libro.getAnio(), libro.getEjemplares(), libro.getDisponibilidad()});
                }
            } catch (Exception ex) {
                // Manejo de otras excepciones, si es necesario
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error: " + ex.getMessage());
            }
        }
    }
    private void cargarLibrosAutor(){
        borrarFilasTabla();
        String autor = jtfBuscarXAutor.getText().trim(); // Elimina espacios en blanco alrededor del nombre
        if (autor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el nombre del autor");
        } else {
            try {
                List<Libro> lista = (ArrayList) ld.buscarLibroPorAutor(autor);
                for (Libro libro : lista) {
                    modelo.addRow(new Object[] {libro.getIdLibro(), libro.getIsbn(), libro.getNombre(), libro.getTipo(), libro.getEditorial(), libro.getAutor(), libro.isEstado(), libro.getAnio(), libro.getEjemplares(), libro.getDisponibilidad()});
                }
            } catch (Exception ex) {
                
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error: " + ex.getMessage());
            }
        }
    }
    private void borrarFilasTabla(){
        int indice = modelo.getRowCount() -1;
        for (int i = indice; i>=0; i--){
            modelo.removeRow(i);
        }
    }
}
