/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoDatos.LectorData;
import Clases.Lector;


import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariel
 */
public class BuscarSocio extends javax.swing.JInternalFrame {
    private ArrayList<Lector> listaLector;
    private ArrayList<Lector> listaLectores;
    private LectorData ld = new LectorData(); 
    private Lector lector = null;
    private DefaultTableModel modelo = new DefaultTableModel();
    
    /**
     * Creates new form BuscarSocio
     */
    public BuscarSocio() {
        initComponents();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlBuscarXDni = new javax.swing.JLabel();
        jtfBuscarXDni = new javax.swing.JTextField();
        jbBuscarDni = new javax.swing.JButton();
        jbListarSocios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLectores = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();

        setResizable(true);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(255, 221, 184));

        jPanel2.setBackground(new java.awt.Color(150, 186, 223));

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 48)); // NOI18N
        jLabel1.setText("Buscar Socios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jlBuscarXDni.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlBuscarXDni.setText("Buscar por DNI");

        jtfBuscarXDni.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jtfBuscarXDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBuscarXDniActionPerformed(evt);
            }
        });

        jbBuscarDni.setBackground(new java.awt.Color(150, 186, 223));
        jbBuscarDni.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbBuscarDni.setText("Buscar");
        jbBuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarDniActionPerformed(evt);
            }
        });

        jbListarSocios.setBackground(new java.awt.Color(150, 186, 223));
        jbListarSocios.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbListarSocios.setText("Listar todos los socios");
        jbListarSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarSociosActionPerformed(evt);
            }
        });

        jtLectores.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jtLectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtLectores);

        jbSalir.setBackground(new java.awt.Color(150, 186, 223));
        jbSalir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbSalir)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlBuscarXDni)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbBuscarDni)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfBuscarXDni, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbListarSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlBuscarXDni))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfBuscarXDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbListarSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jbBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBuscarXDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBuscarXDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBuscarXDniActionPerformed

    private void jbBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarDniActionPerformed
        // TODO add your handling code here:
        cargarDatosLectores();
        
    }//GEN-LAST:event_jbBuscarDniActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbListarSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarSociosActionPerformed
        // TODO add your handling code here:
        borrarFilasTabla();
        List<Lector> lista = (ArrayList) ld.listarLectores();
        for(Lector lector: lista){
            modelo.addRow(new Object[] {lector.getIdLector(), lector.getNombre(), lector.getDni(), lector.getDomicilio(), lector.getTelefono(), lector.isEstado(), lector.getMail()});
        }
    }//GEN-LAST:event_jbListarSociosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscarDni;
    private javax.swing.JButton jbListarSocios;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlBuscarXDni;
    private javax.swing.JTable jtLectores;
    private javax.swing.JTextField jtfBuscarXDni;
    // End of variables declaration//GEN-END:variables

    private void armarCabeceraTabla(){
        ArrayList <Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID Lector");
        filaCabecera.add("Nombre");
        filaCabecera.add("DNI");
        filaCabecera.add("Domicilio");
        filaCabecera.add("Teléfono");
        filaCabecera.add("Estado");
        filaCabecera.add("Mail");
        for(Object it: filaCabecera){
            modelo.addColumn(it);
        }
        jtLectores.setModel(modelo);
    }
        private void cargarDatosLectores(){
        borrarFilasTabla();
            try{
                Integer dni=Integer.parseInt(jtfBuscarXDni.getText());
                String dniString = dni+"";
                lector = ld.buscarLectorPorDni(dniString);
                modelo.addRow(new Object[] {lector.getIdLector(), lector.getNombre(), lector.getDni(), lector.getDomicilio(), lector.getTelefono(), lector.isEstado(), lector.getMail()});
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");
            }
        }
        private void borrarFilasTabla(){
            int indice = modelo.getRowCount() -1;
            for (int i = indice; i>=0; i--){
                modelo.removeRow(i);
            }
        }

}

