/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author ariel
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiActualizarDatos = new javax.swing.JMenuItem();
        jmiBuscarSocios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiIngresoLibros = new javax.swing.JMenuItem();
        jmiActualizarLibros = new javax.swing.JMenuItem();
        jmiBuscarLibros = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiSp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(255, 221, 184));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(150, 186, 223));
        jMenuBar1.setForeground(new java.awt.Color(150, 186, 223));
        jMenuBar1.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(150, 186, 223));
        jMenu1.setText("Socios");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem1.setText("Agregar Socios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jmiActualizarDatos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jmiActualizarDatos.setText("Actualizar datos");
        jmiActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiActualizarDatosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiActualizarDatos);

        jmiBuscarSocios.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jmiBuscarSocios.setText("Buscar socios");
        jmiBuscarSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarSociosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiBuscarSocios);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(150, 186, 223));
        jMenu2.setText("Libros");
        jMenu2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jmiIngresoLibros.setBackground(new java.awt.Color(150, 186, 223));
        jmiIngresoLibros.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jmiIngresoLibros.setText("Ingreso de libros");
        jmiIngresoLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIngresoLibrosActionPerformed(evt);
            }
        });
        jMenu2.add(jmiIngresoLibros);

        jmiActualizarLibros.setBackground(new java.awt.Color(150, 186, 223));
        jmiActualizarLibros.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jmiActualizarLibros.setText("Actualizar libros");
        jmiActualizarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiActualizarLibrosActionPerformed(evt);
            }
        });
        jMenu2.add(jmiActualizarLibros);

        jmiBuscarLibros.setBackground(new java.awt.Color(150, 186, 223));
        jmiBuscarLibros.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jmiBuscarLibros.setText("Buscar libros");
        jmiBuscarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarLibrosActionPerformed(evt);
            }
        });
        jMenu2.add(jmiBuscarLibros);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(150, 186, 223));
        jMenu3.setText("Préstamos");
        jMenu3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jmiSp.setBackground(new java.awt.Color(150, 186, 223));
        jmiSp.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jmiSp.setText("Solicitar préstamos");
        jmiSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSpActionPerformed(evt);
            }
        });
        jMenu3.add(jmiSp);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarSocio as =new AgregarSocio();
        as.setVisible(true);
        escritorio.add(as);
        escritorio.moveToFront(as);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiActualizarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiActualizarLibrosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ActualizarLibros al =new ActualizarLibros();
        al.setVisible(true);
        escritorio.add(al);
        escritorio.moveToFront(al);                               
    }//GEN-LAST:event_jmiActualizarLibrosActionPerformed

    private void jmiBuscarSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarSociosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BuscarSocio bs = new BuscarSocio();
        bs.setVisible(true);
        escritorio.add(bs);
        escritorio.moveToFront(bs);
    }//GEN-LAST:event_jmiBuscarSociosActionPerformed

    private void jmiBuscarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarLibrosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BuscarLibros bl = new BuscarLibros();
        bl.setVisible(true);
        escritorio.add(bl);
        escritorio.moveToFront(bl);
    }//GEN-LAST:event_jmiBuscarLibrosActionPerformed

    private void jmiIngresoLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIngresoLibrosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        IngresarLibros il = new IngresarLibros();
        il.setVisible(true);
        escritorio.add(il);
        escritorio.moveToFront(il);
    }//GEN-LAST:event_jmiIngresoLibrosActionPerformed

    private void jmiActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiActualizarDatosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ActualizarDatos al = new ActualizarDatos();
        al.setVisible(true);
        escritorio.add(al);
        escritorio.moveToFront(al);
    }//GEN-LAST:event_jmiActualizarDatosActionPerformed

    private void jmiSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSpActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        SolicitarPrestamos sp = new SolicitarPrestamos();
        sp.setVisible(true);
        escritorio.add(sp);
        escritorio.moveToFront(sp);
    }//GEN-LAST:event_jmiSpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmiActualizarDatos;
    private javax.swing.JMenuItem jmiActualizarLibros;
    private javax.swing.JMenuItem jmiBuscarLibros;
    private javax.swing.JMenuItem jmiBuscarSocios;
    private javax.swing.JMenuItem jmiIngresoLibros;
    private javax.swing.JMenuItem jmiSp;
    // End of variables declaration//GEN-END:variables
}
