/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import AccesoDatos.LectorData;
import AccesoDatos.LibroData;
import AccesoDatos.PrestamoData;
import Clases.Lector;
import Clases.Libro;
import Clases.Prestamos;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ariel
 */
public class SolicitarPrestamos extends javax.swing.JInternalFrame {
    private LectorData lectorData = new LectorData();
    private Lector lector = null;
    private LibroData libroData = new LibroData();
    private Libro libro = null; 
    private PrestamoData pd = new PrestamoData();
    private Prestamos prestamo = null;
    private DefaultTableModel modelo;
    private ArrayList<Prestamos> listaPrestamos;

    /**
     * Creates new form SolicitarPrestamos
     */
    public SolicitarPrestamos() {
        initComponents();
        lectorData = new LectorData(); 
        libroData = new LibroData(); 
        modelo = new DefaultTableModel();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlDni = new javax.swing.JLabel();
        jtfDni = new javax.swing.JTextField();
        jlIdLibro = new javax.swing.JLabel();
        jtfIdLibro = new javax.swing.JTextField();
        jbSolicitarPrestamo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbNuevo = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setResizable(true);
        setPreferredSize(new java.awt.Dimension(850, 550));

        jPanel1.setBackground(new java.awt.Color(255, 221, 184));

        jPanel2.setBackground(new java.awt.Color(150, 186, 223));
        jPanel2.setPreferredSize(new java.awt.Dimension(840, 100));

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 48)); // NOI18N
        jLabel1.setText("Solicitud de Préstamos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(150, 150, 150))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jlDni.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlDni.setText("DNI del Socio");

        jtfDni.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jlIdLibro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlIdLibro.setText("ID del libro");

        jtfIdLibro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jbSolicitarPrestamo.setBackground(new java.awt.Color(150, 186, 223));
        jbSolicitarPrestamo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbSolicitarPrestamo.setText("Solicitar préstamo");
        jbSolicitarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSolicitarPrestamoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("INFORMACIÓN DEL PRÉSTAMO");

        jTable1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbNuevo.setBackground(new java.awt.Color(150, 186, 223));
        jbNuevo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbNuevo.setText("Nuevo Préstamo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(150, 186, 223));
        jbSalir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(150, 186, 223));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setText("Devolver libro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(150, 186, 223));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setText("Mostrar préstamos en tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(269, 269, 269))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalir))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlIdLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbSolicitarPrestamo)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDni)
                    .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIdLibro)
                    .addComponent(jtfIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSolicitarPrestamo))
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbSalir)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSolicitarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSolicitarPrestamoActionPerformed
        // TODO add your handling code here:
        try{
            String dni = jtfDni.getText();
            Integer idLibro = Integer.parseInt(jtfIdLibro.getText());
            if(dni.isEmpty()){
                JOptionPane.showMessageDialog(this, "No debe haber campos vacíos");
            } else{
                lector = lectorData.buscarLectorPorDni(dni);
                libro = libroData.buscarLibroPorId(idLibro);
                pd.solicitarLibro(lector, libro);
                //borrarFilasTabla();
                //List<Prestamos> lista = (ArrayList) pd.listarPrestamosActivos();
                //for(Prestamos prestamo: lista){
                    //modelo.addRow(new Object[] {prestamo.getIdPrestamo(), prestamo.getFechaInicio(), prestamo.getFechaFin(), prestamo.getLibro().getIdLibro(), prestamo.getLector().getDni(), lector.isEstado()});
                //}
                //pd.buscarPrestamoReciente(idLibro, dni);
                //modelo.addRow(new Object[] {prestamo.getIdPrestamo(), prestamo.getFechaInicio(), prestamo.getFechaFin(), prestamo.getLibro().getIdLibro(), prestamo.getLector().getDni(), prestamo.isEstado()});
            }
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Debe ingresar números enteros en los campos númericos");
        }
    }//GEN-LAST:event_jbSolicitarPrestamoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos(); 
        borrarFilasTabla();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String dni = jtfDni.getText();
            Integer idLibro = Integer.parseInt(jtfIdLibro.getText());
            if(dni.isEmpty()){
                JOptionPane.showMessageDialog(this, "No debe haber campos vacíos");
            } else{
                lector = lectorData.buscarLectorPorDni(dni);
                libro = libroData.buscarLibroPorId(idLibro);
                pd.devolverLibro(lector, libro);

            }
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Debe ingresar números enteros en los campos númericos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        List<Prestamos> lista = (ArrayList) pd.listarPrestamosActivos();
        lista.forEach((prestamo) -> {
            modelo.addRow(new Object[] {prestamo.getIdPrestamo(), prestamo.getFechaInicio(), prestamo.getFechaFin(), prestamo.getLibro().getIdLibro(), prestamo.getLector().getDni(), prestamo.isEstado()});
        });
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSolicitarPrestamo;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlIdLibro;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfIdLibro;
    // End of variables declaration//GEN-END:variables
    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID Préstamo");
        filaCabecera.add("Fecha de préstamo");
        filaCabecera.add("Fecha de devolución");
        filaCabecera.add("ID Libro");
        filaCabecera.add("DNI Socio");
        filaCabecera.add("Estado del préstamo");
        for (Object it: filaCabecera){
            modelo.addColumn(it);
        }
        jTable1.setModel(modelo);
        
        
    }
        
    private void limpiarCampos(){
        jtfIdLibro.setText("");
        jtfDni.setText("");
        libro = null;
        lector = null;
    }
    
    private void borrarFilasTabla(){
        int indice = modelo.getRowCount()-1;
        
        for (int i = indice;i>=0;i--){
            modelo.removeRow(i);
        }
    }

}
